name: date_picker_textfield_example
description: Example project demonstrating the use of date_picker_textfield.
publish_to: "none" # Evita publicar esta parte del ejemplo como paquete.
environment:
  sdk: ">=2.19.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  date_picker_textfield:
    path: ../ # Usa el paquete localmente durante el desarrollo.
