name: date_picker_bottom_sheet
description: A Flutter package providing a customizable TextFormField with an integrated date picker presented in a bottom sheet, ideal for seamless date selection in forms and applications.
version: 1.0.1
homepage: https://github.com/absagarcia/date_picker_textfield

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
