name: date_picker_textfield
description: A customizable TextFormField with a built-in date picker.
version: 1.0.0
homepage: https://github.com/tuusuario/date_picker_textfield

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
