# Workflow for Flutter package with Pub.dev validation
name: Flutter Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Verify code formatting
      - name: Verify formatting
        run: flutter format --set-exit-if-changed .

      # Analyze code
      - name: Analyze code
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Install dependencies
        run: flutter pub get

      # Publish to Pub.dev
      - name: Publish package
        env:
          PUB_TOKEN: ${{ secrets.PUB_TOKEN }}
        run: flutter pub publish --dry-run
